article/urls.py
# 引入path
from django.urls import path
from django.contrib import admin

from . import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    path('admin/', admin.site.urls),
    # 文章列表
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 写文章
    path('article-create/', views.article_create, name='article_create'),
    # 删除文章
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # 安全删除文章
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    # 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    # 点赞 +1
    path('increase-likes/<int:id>/', views.IncreaseLikesView.as_view(), name='increase_likes'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论，处理一级回复
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
    # 新增代码，处理二级回复
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply')
]

my_blog/urls.py
from django.contrib import admin
# 记得引入include
from django.urls import path, include
# 新引入的模块
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
# 存放映射关系的列表
urlpatterns = [
    path('admin/', admin.site.urls),

    # 新增代码，配置app的url
    path('article/', include('article.urls', namespace='article')),
    # 用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # 重置密码
    path('password-reset/', include('password_reset.urls')),
    # 评论
    path('comment/', include('comment.urls', namespace='comment')),
    # 通知
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # 消息
    path('notice/', include('notice.urls', namespace='notice')),
    # 三方登录
    # path('accounts/', include('allauth.urls')),
]

# #添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.user_register, name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    # 用户信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# 记得导入
from django.urls import reverse
from taggit.managers import TaggableManager
from PIL import Image


class ArticleColumn(models.Model):
    """
    栏目的 Model
    """
    # 栏目标题
    title = models.CharField(max_length=100, blank=True)
    # 创建时间
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    total_views = models.PositiveIntegerField(default=0)

    # 文章标签
    tags = TaggableManager(blank=True)
    # 文章标题图
    avatar = models.ImageField(upload_to='article/%Y%m%d/', blank=True)
    # 新增点赞数统计
    likes = models.PositiveIntegerField(default=0)
    # 文章栏目的 “一对多” 外键
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

        # 保存时处理图片
    def save(self, *args, **kwargs):
        # 调用原有的 save() 的功能
        article = super(ArticlePost, self).save(*args, **kwargs)

        # 固定宽度缩放图片大小
        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x, y) = image.size
            new_x = 400
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.avatar.path)

        return article

    def was_created_recently(self):
        # 若文章是"最近"发表的，则返回 True
        diff = timezone.now() - self.created
        if diff.days == 0 and 0 <= diff.seconds < 60:
            return True
        else:
            return False

article/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import ArticlePost


# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        # fields = ('title', 'body', 'tags')
        fields = ('title', 'body', 'tags', 'avatar')

article/views.py
# 引入markdown模块
import markdown
# 引入评论表单
from comment.forms import CommentForm
# 引入评论模型
from comment.models import Comment
# 引入User模型
from django.contrib.auth.models import User
# 引入分页模块
from django.core.paginator import Paginator
# 引入 Q 对象
from django.db.models import Q
# 引入HttpResponse
from django.http import HttpResponse
# 引入redirect重定向模块
from django.shortcuts import render, redirect
from django.views import View

# 引入刚才定义的ArticlePostForm表单类
from .forms import ArticlePostForm
from .models import ArticlePost, ArticleColumn


# 文章详情
def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    # 取出文章评论
    comments = Comment.objects.filter(article=id)

    # Markdown 语法渲染
    md = markdown.Markdown(
        extensions=[
            # 包含 缩写、表格等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
            # 目录扩展
            'markdown.extensions.toc',
        ]
    )

    # 浏览量 +1
    article.total_views += 1
    article.save(update_fields=['total_views'])

    # 将markdown语法渲染成html样式
    article.body = markdown.markdown(article.body,
                                     extensions=[
                                         # 包含 缩写、表格等常用扩展
                                         'markdown.extensions.extra',
                                         # 语法高亮扩展
                                         'markdown.extensions.codehilite',
                                         # 目录扩展
                                         'markdown.extensions.toc',
                                     ])
    # 添加自定义字体样式
    article.body = "<style>body { font-family: '华文细黑', sans-serif; font-size: 20px; }</style>" + article.body

    # 引入评论表单
    comment_form = CommentForm()

    # 添加comments上下文
    context = {'article': article, 'toc': md.toc, 'comments': comments,
               'comment_form': comment_form,
               }

    return render(request, 'article/detail.html', context)


# 写文章的视图
def article_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        # article_post_form = ArticlePostForm(data=request.POST)
        # 增加 request.FILES
        article_post_form = ArticlePostForm(request.POST, request.FILES)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            # 指定数据库中 id=1 的用户为作者
            # 如果你进行过删除数据表的操作，可能会找不到id=1的用户
            # 此时请重新创建用户，并传入此用户的id
            new_article.author = User.objects.get(id=request.user.id)
            # 判断用户是否提交栏目
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            # 将新文章保存到数据库中
            new_article.save()
            # 新增代码，保存 tags 的多对多关系
            article_post_form.save_m2m()
            # 完成后返回到文章列表
            return redirect("article:article_list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 获取栏目列表
        columns = ArticleColumn.objects.all()
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文
        context = {'article_post_form': article_post_form, 'columns': columns}
        # 返回模板
        return render(request, 'article/create.html', context)


# 删文章
def article_delete(request, id):
    # 根据 id 获取需要删除的文章
    article = ArticlePost.objects.get(id=id)

    # 过滤非作者的用户
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")

    # 调用.delete()方法删除文章
    article.delete()
    # 完成删除后返回文章列表
    return redirect("article:article_list")


# 安全删除文章
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许post请求")


# 更新文章
def article_update(request, id):
    """
    更新文章的视图函数
    通过POST方法提交表单，更新titile、body字段
    GET方法进入初始表单页面
    id： 文章的 id
    """
    # 获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=id)

    # 过滤非作者的用户
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")

    # 判断用户是否为 POST 提交表单数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 判断用户是否提交栏目
            if request.POST['column'] != 'none':
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None

            # 保存新写入的 title、body 数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            # 完成后返回到修改后的文章中。需传入文章的 id 值
            return redirect("article:article_detail", id=id)
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    # 如果用户 GET 请求获取数据
    else:
        # 获取栏目列表
        columns = ArticleColumn.objects.all()

        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文，将 article 文章对象也传递进去，以便提取旧的内容
        context = {
            'article': article,
            'article_post_form': article_post_form,
            'columns': columns,
        }
        # 将响应返回到模板中
        return render(request, 'article/update.html', context)


def article_list(request):
    # 修改变量名称（articles -> article_list）
    article_list = ArticlePost.objects.all()

    # 每页显示 1 篇文章
    paginator = Paginator(article_list, 1)
    # 获取 url 中的页码
    page = request.GET.get('page')
    # 将导航对象相应的页码内容返回给 articles
    articles = paginator.get_page(page)

    context = {'articles': articles}
    return render(request, 'article/list.html', context)


# 重写文章列表
def article_list(request):
    # 根据GET请求中查询条件
    # 返回不同排序的对象数组
    if request.GET.get('order') == 'total_views':
        article_list = ArticlePost.objects.all().order_by('-total_views')
        order = 'total_views'
    else:
        article_list = ArticlePost.objects.all()
        order = 'normal'

    paginator = Paginator(article_list, 3)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    # 修改此行
    context = {'articles': articles, 'order': order}

    return render(request, 'article/list.html', context)


def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    # 用户搜索逻辑
    if search:
        if order == 'total_views':
            # 用 Q对象 进行联合搜索
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            ).order_by('-total_views')
        else:
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
    else:
        # 将 search 参数重置为空
        search = ''
        if order == 'total_views':
            article_list = ArticlePost.objects.all().order_by('-total_views')
        else:
            article_list = ArticlePost.objects.all()

    paginator = Paginator(article_list, 3)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    # 增加 search 到 context
    context = {'articles': articles, 'order': order, 'search': search}

    return render(request, 'article/list.html', context)


def article_list(request):
    # 从 url 中提取查询参数
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    # 初始化查询集
    article_list = ArticlePost.objects.all()

    # 搜索查询集
    if search:
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''

    # 栏目查询集
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

    # 标签查询集
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    # 查询集排序
    if order == 'total_views':
        article_list = article_list.order_by('-total_views')

    # 分页器
    paginator = Paginator(article_list, 5)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    # 需要传递给模板（templates）的对象
    context = {
        'articles': articles,
        'order': order,
        'search': search,
        'column': column,
        'tag': tag,
    }

    return render(request, 'article/list.html', context)


# 点赞数 +1
class IncreaseLikesView(View):
    def post(self, request, *args, **kwargs):
        article = ArticlePost.objects.get(id=kwargs.get('id'))
        article.likes += 1
        article.save()
        return HttpResponse('success')

templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
  <div class="row">
    <div class="col-12">
      <br />
      <!-- 提交文章的表单 -->
      <form method="post" action="." enctype="multipart/form-data">
        <!-- Django中需要POST数据的地方都必须有csrf_token -->
        {% csrf_token %}

        <!-- 文章标题图 -->
        <div class="form-group">
            <label for="avatar">标题图</label>
            <input type="file" class="form-control-file" name="avatar" id="avatar">
        </div>

        <!-- 文章标题 -->
        <div class="form-group">
          <!-- 标签 -->
          <label for="title">文章标题</label>
          <!-- 文本框 -->
          <input type="text" class="form-control" id="title" name="title" />
        </div>

          <!-- 文章栏目 -->
            <div class="form-group">
                <label for="column">栏目</label>
                <select class="form-control"
                        id="column"
                        name="column"
                >
                        <option value="none">请选择栏目..</option>
                    {% for column in columns %}
                        <option value="{{ column.id }}">{{ column }}</option>
                    {% endfor %}
                </select>
            </div>

       <!-- 文章标签 -->
        <div class="form-group">
            <label for="tags">标签</label>
            <input type="text"
                   class="form-control col-3"
                   id="tags"
                   name="tags"
            >
        </div>

        <!-- 文章正文 -->
        <div class="form-group">
          <label for="body">文章正文</label>
          <!-- 文本区域 -->
          <textarea
            type="text"
            class="form-control"
            id="body"
            name="body"
            rows="12"
          ></textarea>
        </div>
        <!-- 提交按钮 -->
        <button type="submit" class="btn btn-primary">完成</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %} 文章详情 {% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}



    <!-- 文章详情 -->
    <div class="container">
        <div class="row">
            <div class="col-9">
                <!-- 标题及作者 -->
                <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
                <div class="col-12 alert alert-success">
                    <div>
                        作者：{{ article.author }}
                        {% if user == article.author %}
                            · <a href="#" onclick="confirm_delete()">删除文章</a>
                            · <a href="{% url "article:article_update" article.id %}">
                            编辑文章
                        </a>
                        {% endif %}
                    </div>

                    <div>
                        浏览：{{ article.total_views }}
                    </div>


                    <!-- 新增一个隐藏的表单 -->
                    <form
                            style="display:none;"
                            id="safe_delete"
                            action="{% url 'article:article_safe_delete' article.id %}"
                            method="POST"
                    >
                        {% csrf_token %}
                        <button type="submit">发送</button>
                    </form>
                </div>


                <!-- 文章正文 -->
                <div class="col-12">

                    <!-- 在 article.body 后加上 |safe 过滤器 -->
                    <p>{{ article.body|safe }}</p>
                </div>

                <!-- 新增点赞按钮 -->
                <div style="text-align:center;" class="mt-4">
                    <button class="btn btn-outline-danger"
                            type="button"
                            onclick="validate_is_like(
                                    '{% url 'article:increase_likes' article.id %}',
                                    {{ article.id }},
                                    {{ article.likes }}
                                    )"
                    >
                        <span>点赞</span>
                        <span>
                            <i class="fas fa-heart"></i>
                        </span>
                        <span id="likes_number">
                            {{ article.likes }}
                        </span>
                    </button>
                </div>
                <!-- 发表评论 -->
                <hr>
                {% if user.is_authenticated %}
                    <div>
                        <form
                                action="{% url 'comment:post_comment' article.id %}"
                                method="POST"
                        >
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="body">
                                    <strong>
                                        我也要发言：
                                    </strong>
                                </label>

                                <div>
                                    {{ comment_form.media }}
                                    {{ comment_form.body }}
                                </div>


                            </div>
                            <!-- 提交按钮 -->
                            <button type="submit" class="btn btn-primary ">发送</button>
                        </form>
                    </div>
                    <br>
                {% else %}
                    <br>
                    <h5 class="row justify-content-center">
                        请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                    </h5>
                    <br>
                {% endif %}


                <!-- 改动 显示评论 部分 -->
                <!-- 不要漏了 load mptt_tags！ -->
                {% load mptt_tags %}
                <h4>共有{{ comments.count }}条评论</h4>
                <div class="row">
                    <!-- 遍历树形结构 -->
                    {% recursetree comments %}
                        <!-- 给 node 取个别名 comment -->
                        {% with comment=node %}
                            <div class="{% if comment.reply_to %}
                        offset-1 col-11
                        {% else %}
                        col-12
                        {% endif %}"
                            >
                                <hr>
                                <p>
                                    <strong style="color: pink">
                                        {{ comment.user }}
                                    </strong>

                                    {% if comment.reply_to %}
                                        <i class="far fa-arrow-alt-circle-right"
                                           style="color: cornflowerblue;"
                                        ></i>
                                        <strong style="color: pink">
                                            {{ comment.reply_to }}
                                        </strong>
                                    {% endif %}

                                </p>
                                <div>{{ comment.body|safe }}</div>

                                <div>
                    <span style="color: gray">
                        {{ comment.created|date:"Y-m-d H:i" }}
                    </span>

                                    <!-- 加载 modal 的按钮 -->
                                    {% if user.is_authenticated %}
                                        <button type="button"
                                                class="btn btn-light btn-sm text-muted"
                                                onclick="load_modal({{ article.id }}, {{ comment.id }})"
                                        >
                                            回复
                                        </button>
                                    {% else %}
                                        <a class="btn btn-light btn-sm text-muted"
                                           href="{% url 'userprofile:login' %}"
                                        >
                                            回复
                                        </a>
                                    {% endif %}
                                </div>

                                <!-- Modal -->
                                <div class="modal fade"
                                     id="comment_{{ comment.id }}"
                                     tabindex="-1"
                                     role="dialog"
                                     aria-labelledby="CommentModalCenter"
                                     aria-hidden="true"
                                >
                                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                        <div class="modal-content" style="height: 480px">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalCenterTitle">
                                                    回复 {{ comment.user }}：</h5>
                                            </div>
                                            <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                        </div>

                                    </div>
                                </div>

                                {% if not comment.is_leaf_node %}
                                    <div class="children">
                                        {{ children }}
                                    </div>
                                {% endif %}
                            </div>


                        {% endwith %}
                    {% endrecursetree %}
                </div>


            </div>
        </div>
    </div>
    </div>



<script src="{% static 'csrf.js' %}"></script>

    <script>
        $('div#article_body table').addClass('table table-bordered');
        $('div#article_body thead').addClass('thead-light');
        $(".django-ckeditor-widget").removeAttr('style');

        // 删除文章的函数
        function confirm_delete() {
            // 调用layer弹窗组件
            layer.open({
                // 弹窗标题
                title: "确认删除",
                // 正文
                content: "确认删除这篇文章吗？",
                // 点击确定按钮后调用的回调函数
                yes: function (index, layero) {
                    // 指定应当前往的 url
                    location.href = '{% url "article:article_delete" article.id %}'
                },
            })
        }

        function confirm_safe_delete() {
            layer.open({
                title: "确认删除",
                content: "确认删除这篇文章吗？",
                yes: function (index, layero) {
                    $('form#safe_delete button').click();
                    layer.close(index);
                }
            })
        }


        // 加载 modal
        function load_modal(article_id, comment_id) {
            let modal_body = '#modal_body_' + comment_id;
            let modal_id = '#comment_' + comment_id;

            // 加载编辑器
            if ($(modal_body).children().length === 0) {
                let content = '<iframe src="/comment/post-comment/' +
                    article_id +
                    '/' +
                    comment_id +
                    '"' +
                    ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' +
                    comment_id +
                    '"></iframe>';
                $(modal_body).append(content);
            }
            ;

            $(modal_id).modal('show');
        }


        // 点赞功能主函数
        function validate_is_like(url, id, likes) {
            // 取出 LocalStorage 中的数据
            let storage = window.localStorage;
            const storage_str_data = storage.getItem("my_blog_data");
            let storage_json_data = JSON.parse(storage_str_data);
            // 若数据不存在，则创建空字典
            if (!storage_json_data) {
                storage_json_data = {}
            }
            ;
            // 检查当前文章是否已点赞。是则 status = true
            const status = check_status(storage_json_data, id);
            if (status) {
                layer.msg('已经点过赞了哟~');
                // 点过赞则立即退出函数
                return;
            } else {
                // 用 Jquery 找到点赞数量，并 +1
                $('span#likes_number').text(likes + 1).css('color', '#dc3545');
            }
            // 用 ajax 向后端发送 post 请求
            $.post(
                url,
                // post 只是为了做 csrf 校验，因此数据为空
                {},
                function (result) {
                    if (result === 'success') {
                        // 尝试修改点赞数据
                        try {
                            storage_json_data[id] = true;
                        } catch (e) {
                            window.localStorage.clear();
                        }
                        ;
                        // 将字典转换为字符串，以便存储到 LocalStorage
                        const d = JSON.stringify(storage_json_data);
                        // 尝试存储点赞数据到 LocalStorage
                        try {
                            storage.setItem("my_blog_data", d);
                        } catch (e) {
                            // code 22 错误表示 LocalStorage 空间满了
                            if (e.code === 22) {
                                window.localStorage.clear();
                                storage.setItem("my_blog_data", d);
                            }
                        }
                        ;
                    } else {
                        layer.msg("与服务器通信失败..过一会儿再试试呗~");
                    }

                }
            );
        };

        // 辅助点赞主函数，验证点赞状态
        function check_status(data, id) {
            // 尝试查询点赞状态
            try {
                if (id in data && data[id]) {
                    return true;
                } else {
                    return false;
                }
            } catch (e) {
                window.localStorage.clear();
                return false;
            }
            ;
        };
    </script>

{% endblock content %}

templates/article/list_card.html
<div class="row mt-2">
    {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
            <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                    <!-- 显示浏览量 -->
                    <span>
                        <small class="col align-self-end" style="color: gray;">
                            浏览: {{ article.total_views }}
                        </small>
                    </span>

                </div>
            </div>
        </div>
    {% endfor %}

</div>

templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                 <!-- 文章栏目 -->
                <div class="form-group">
                    <label for="column">栏目</label>
                    <select class="form-control"
                            id="column"
                            name="column"
                    >
                            <option value="none">请选择栏目..</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}"
                                {% if column.id == article.column.id %}
                                    selected
                                {% endif %}
                            >
                                {{ column }}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}